### ISSUE TITLE
Create a "project"

### ISSUE THREAD

**Issue by leocastroz** [SteveYuOWO/vue-hot-toast-ui#1]
- Create a project on "GitHub Projects" to attach PR's as activities to cards - **_[ priority ]_**

**_ex:_** 
![image](https://github.com/SteveYuOWO/vue-hot-toast-ui/assets/72839343/257ec86a-feca-4ca1-9ab6-0627cee69c7c)

**Comment by SteveYuOWO** [comment]
https://github.com/users/SteveYuOWO/projects/3/views/1

Thanks to your advice, I created a board @leocastroz

**Comment by SteveYuOWO** [comment]
I invited you to join the Github Project. You can give me some tasks to push the project forward. @leocastroz

**Comment by j0rgedev** [comment]
Hey @leocastroz will you use nuxt in this project?

**Comment by leocastroz** [comment]
Thanks @SteveYuOWO, I'll think of something from the project and I'll relate it to you. No @j0rgedev, "Steve" created it in vue.js 3, as we have already started we believe we can keep going.

_It will be simple and intuitive for the end user._

**Comment by j0rgedev** [comment]
Sound good @leocastroz I'd love to contribute to this project as well!

**Comment by leocastroz** [comment]
**[ done ]**

- [x] Creating a project plan.
- [x] Adding collaborators (@SteveYuOWO, @leocastroz , @j0rgedev ).
